"""initial_schema

Revision ID: 788a003b4d67
Revises: 
Create Date: 2026-02-10 09:17:57.514070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788a003b4d67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('destinations', sa.Text(), nullable=True),
    sa.Column('include_database', sa.Boolean(), nullable=False),
    sa.Column('include_configs', sa.Boolean(), nullable=False),
    sa.Column('include_themes', sa.Boolean(), nullable=False),
    sa.Column('include_plugins', sa.Boolean(), nullable=False),
    sa.Column('include_achievements', sa.Boolean(), nullable=False),
    sa.Column('include_controller_mappings', sa.Boolean(), nullable=False),
    sa.Column('max_retention_days', sa.Integer(), nullable=False),
    sa.Column('max_backup_count', sa.Integer(), nullable=False),
    sa.Column('encrypt', sa.Boolean(), nullable=False),
    sa.Column('compress', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_game_id', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('total_achievements', sa.Integer(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_game_id', name='uq_platform_game')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('sync_date', sa.DateTime(), nullable=False),
    sa.Column('games_synced', sa.Integer(), nullable=False),
    sa.Column('achievements_found', sa.Integer(), nullable=False),
    sa.Column('achievements_unlocked', sa.Integer(), nullable=False),
    sa.Column('new_unlocks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('icon_locked_url', sa.Text(), nullable=True),
    sa.Column('global_percentage', sa.Float(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('is_rare', sa.Boolean(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'achievement_id', name='uq_game_achievement')
    )
    op.create_index('ix_achievements_game_rare', 'achievements', ['game_id', 'is_rare'], unique=False)
    op.create_table('backup_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('parent_backup_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('backup_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('compressed_size', sa.Integer(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_backup_id'], ['backup_jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['backup_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_jobs_created_type', 'backup_jobs', ['created_at', 'backup_type'], unique=False)
    op.create_table('achievement_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('platform_user_id', sa.String(length=100), nullable=False),
    sa.Column('game_name', sa.String(length=500), nullable=False),
    sa.Column('achievement_name', sa.String(length=500), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('backup_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backup_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restore_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backup_job_id', sa.Integer(), nullable=False),
    sa.Column('restored_at', sa.DateTime(), nullable=False),
    sa.Column('items_restored', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('selective', sa.Boolean(), nullable=False),
    sa.Column('restored_categories', sa.Text(), nullable=True),
    sa.Column('target_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['backup_job_id'], ['backup_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('platform_user_id', sa.String(length=100), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlock_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('achievement_id', 'platform_user_id', name='uq_user_achievement')
    )
    op.create_index('ix_user_achievements_lookup', 'user_achievements', ['achievement_id', 'platform_user_id', 'is_unlocked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_achievements_lookup', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('restore_logs')
    op.drop_table('backup_files')
    op.drop_table('achievement_notifications')
    op.drop_index('ix_backup_jobs_created_type', table_name='backup_jobs')
    op.drop_table('backup_jobs')
    op.drop_index('ix_achievements_game_rare', table_name='achievements')
    op.drop_table('achievements')
    op.drop_table('sync_logs')
    op.drop_table('games')
    op.drop_table('backup_profiles')
    # ### end Alembic commands ###
